name: Test Hashnode Publisher Validation

on:
  workflow_dispatch:

  pull_request:
    paths:
      - 'src/**'
      - 'action.yml'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'action.yml'
      - '.github/workflows/**'

jobs:
  test-validation:
    name: Test Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build action
        run: |
          npm run build
          echo "Checking build output..."
          ls -la dist/

          # Check for bundled output
          if [ ! -f "dist/index.js" ]; then
            echo "❌ Missing bundled output: dist/index.js"
            exit 1
          fi
          echo "✅ Found bundled output: dist/index.js"

      - name: Create test content
        run: |
          mkdir -p tmp-blog/subdir
          # Create multiple test files
          cat > tmp-blog/hello-world.md <<EOL
          ---
          title: "Hello World"
          tags: ["test", "hello"]
          ---

          This is a test article for the Hashnode Publisher action.
          EOL

          cat > tmp-blog/subdir/another-article.md <<EOL
          ---
          title: "Another Article"
          tags: ["test", "article"]
          ---

          This is another test article in a subdirectory.
          EOL

          # Create an invalid file to test error handling
          cat > tmp-blog/invalid.md <<EOL
          ---
          title: "Invalid Article"
          tags: ["toolongtagtoolongtagtoolong"]
          ---

          Too short.
          EOL

      - name: Run validation
        id: validate
        run: |
          set +e
          OUTPUT=$(node dist/index.js validate tmp-blog/ --recursive --continue-on-error)
          STATUS=$?
          echo "$OUTPUT"
          echo "exit_code=$STATUS" >> $GITHUB_OUTPUT
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          exit $STATUS

      - name: Verify test results
        run: |
          echo "✅ Validation test completed"
          echo "Test directory: tmp-blog/"
          echo "Mode: Recursive validation with continue-on-error"
          echo "Test files:"
          find tmp-blog -type f -name "*.md" -exec echo "  - {}" \;

          if echo "${{ steps.validate.outputs.output }}" | grep -q '❌'; then
            echo "Detected validation errors as expected."
          else
            echo "No validation errors detected."
          fi
